services:
  adguardhome:
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - /mnt/data/adguard/work:/opt/adguardhome/work
      - /mnt/data/adguard/conf:/opt/adguardhome/conf
    ports:
      # DNS/Local Network Services
      - "53:53/tcp"
      - "53:53/udp"
      
      # HTTP/S Web Interface
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      
      # Management/Custom Ports
      - "3000:3000/tcp"
      - "853:853/tcp"
      
      # Other UDP/TCP Services
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"